print(" ")
print(" ")
print(" ")
print(" ")
print(" gg    gg     gg    eeeeeee   cc          cc           ooooooooo     mm         mm     eeeeeee      ")
print(" gg    gg     gg    ee        cc          cc           oo     oo     mm mm   mm mm     ee           ")
print("  gg gg   gg gg     eeeeeee   cc          cc           oo     oo     mm    mm   mm     eeeeeee      ")
print("   gg      gg       ee        cc          cc           oo     oo     mm         mm     ee           ")
print("   gg      gg       eeeeeee   cccccccc    cccccccc     ooooooooo     mm         mm     eeeeeee      ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")

print("welcome to crackmes")

r = input("password = ")
if r == "17052311":
    print("password is correct")
else :
    print("password is incorrect")


input("press enter to exit")